author: Kazuyuki Hiroshiba
description: Hiroshibaのブログです。
keyword:
favicon: /images/favicon.png
banner: images/banner.png

excerpt_link: Read More

menu:
 # Home: /
 # Tags: /tags/
 Twitter: https://twitter.com/hiho_karuta
 Archives: /archives/
 Github: https://github.com/Hiroshiba
 # Projects:
 # About: /about/

# catalog
catalog: false

google_analytics: UA-141253083-1

about:
  banner:
  avatar: https://avatars.githubusercontent.com/Hiroshiba
  description: 東京で働くシステムエンジニア。
  weibo_username:
  twitter_username: hiho_karuta
  github_username: Hiroshiba
  zhihu_username:
  douban_username:
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
