author: Kazuyuki Hiroshiba
description: Hiroshibaのブログです。
keyword:
favicon: /images/favicon.png
banner: images/banner.png

excerpt_link: Read More

menu:
 # Home: /
 # Tags: /tags/
 Twitter: https://twitter.com/hiho_karuta
 Archives: /archives/
 Github: https://github.com/Hiroshiba
 # Projects:
 # About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: false

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment or uyan

# comment:

# gitment_owner:
# gitment_repo:
# gitment_oauth_id:
# gitment_oauth_secret:

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

# baidu_id:

google_analytics: UA-141253083-1

about:
  banner:
  avatar: https://avatars.githubusercontent.com/Hiroshiba
  description: 東京で働くプログラマ。
  weibo_username:
  twitter_username: hiho_karuta
  github_username: Hiroshiba
  zhihu_username:
  douban_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
